//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppWebServiceTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceKoosSoap")]
    public interface WebServiceKoosSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldResponse HelloWorld(WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AddTwoIntsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoInts", ReplyAction="*")]
        WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsResponse AddTwoInts(WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoInts", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsResponse> AddTwoIntsAsync(WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoIntsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoInts", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequestBody Body;
        
        public AddTwoIntsRequest() {
        }
        
        public AddTwoIntsRequest(WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoIntsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int valA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int valB;
        
        public AddTwoIntsRequestBody() {
        }
        
        public AddTwoIntsRequestBody(int valA, int valB) {
            this.valA = valA;
            this.valB = valB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoIntsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoIntsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsResponseBody Body;
        
        public AddTwoIntsResponse() {
        }
        
        public AddTwoIntsResponse(WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoIntsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTwoIntsResult;
        
        public AddTwoIntsResponseBody() {
        }
        
        public AddTwoIntsResponseBody(string AddTwoIntsResult) {
            this.AddTwoIntsResult = AddTwoIntsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceKoosSoapChannel : WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceKoosSoapClient : System.ServiceModel.ClientBase<WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap>, WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap {
        
        public WebServiceKoosSoapClient() {
        }
        
        public WebServiceKoosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceKoosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKoosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKoosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldResponse WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap.HelloWorld(WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequestBody();
            WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldResponse retVal = ((WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldResponse> WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap.HelloWorldAsync(WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsAppWebServiceTest.ServiceReference1.HelloWorldRequestBody();
            return ((WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsResponse WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap.AddTwoInts(WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequest request) {
            return base.Channel.AddTwoInts(request);
        }
        
        public string AddTwoInts(int valA, int valB) {
            WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequest inValue = new WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequest();
            inValue.Body = new WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequestBody();
            inValue.Body.valA = valA;
            inValue.Body.valB = valB;
            WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsResponse retVal = ((WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap)(this)).AddTwoInts(inValue);
            return retVal.Body.AddTwoIntsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsResponse> WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap.AddTwoIntsAsync(WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequest request) {
            return base.Channel.AddTwoIntsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsResponse> AddTwoIntsAsync(int valA, int valB) {
            WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequest inValue = new WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequest();
            inValue.Body = new WindowsFormsAppWebServiceTest.ServiceReference1.AddTwoIntsRequestBody();
            inValue.Body.valA = valA;
            inValue.Body.valB = valB;
            return ((WindowsFormsAppWebServiceTest.ServiceReference1.WebServiceKoosSoap)(this)).AddTwoIntsAsync(inValue);
        }
    }
}
